# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#for testing purpose

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: ArchiveFiles@2
  displayName: 'Zip playbook including roles'
  inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(System.TeamProject)-$(Build.DefinitionName)-$(Build.BuildId).zip'
      replaceExistingArchive: true
      verbose: true
      quiet: false
- task: PublishBuildArtifacts@1
  displayName: 'Publish playbook as Build Artifact'
  inputs:
     pathtoPublish: '$(Build.ArtifactStagingDirectory)'
     artifactName: '$(System.TeamProject)-$(Build.DefinitionName)'
     publishLocation: 'container'
     parallel: false
